=== masacdotio/251402-MGNBALL/251402-MGNBALL/Packages/Beckhoff.TwinCAT.HMI.SqliteHistorize.22.0.7563/runtimes/linux-x64/native/TcHmiSqliteHistorize.Schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "definitions": {
    "stringTypeArray": {
      "configDescription": "descStringTypeArray",
      "oneOf": [
        {
          "type": "string",
          "format": "timespan",
          "configDescription": "descStringTypeArrayTimespan"
        },
        {
          "type": "string",
          "format": "date-time",
          "configDescription": "descStringTypeArrayTimestamp"
        },
        {
          "type": "string",
          "enum": [ "Null", "First", "Latest" ],
          "configDescription": "descStringTypeArrayStartPoint"
        }
      ]
    }
  },
  "properties": {
    "historizedSymbolList": {
      "configDescription": "descHistorizedSymbolList",
      "defaultConfigurable": true,
      "type": "object",
      "propertyOrder": 1,
      "additionalProperties": {
        "configDescription": "descHistorizedSymbol",
        "title": "TITLE_HISTORIZE_SYMBOL",
        "keyOptionMethod": {
          "symbol": "ListSymbolNames"
        },
        "type": "object",
        "properties": {
          "version": {
            "type": "number",
            "optionMethodAllowCustom": false,
            "optionMethod": {
              "symbol": "GetSchema::{key}",
              "version": 2.0,
              "writeValue": {
                "symbol": {
                  "$data": "#/properties/historizedSymbolList/additionalProperties"
                },
                "resolve": "AllVersions"
              },
              "orderBy": "DESC"
            },
            "default": 1.0
          },
          "maxEntries": {
            "type": "integer",
            "minimum": 1,
            "default": 10000
          },
          "interval": {
            "type": "string",
            "format": "timespan",
            "default": "PT1S",
            "formatMinimum": "PT0.01S"
          },
          "recordingEnabled": {
            "type": "boolean",
            "default": true
          },
          "rowLimit": {
            "visibility": "HideInEngineering",
            "type": "integer",
            "minimum": 1,
            "default": 100000
          }
        },
        "required": [ "maxEntries", "interval", "recordingEnabled", "rowLimit" ],
        "additionalProperties": false
      }
    },
    "enableBackup": {
      "configDescription": "descEnableBackup",
      "propertyOrder": 2,
      "type": "boolean",
      "default": false,
      "defaultConfigurable": true
    },
    "maxBackups": {
      "configDescription": "descMaxBackup",
      "propertyOrder": 3,
      "type": "integer",
      "minimum": 1,
      "default": 1,
      "defaultConfigurable": true
    },
    "inMemory": {
      "propertyOrder": 4,
      "type": "boolean",
      "default": false,
      "configDescription": "descInMemory",
      "defaultConfigurable": true
    },
    "vacuumOnStartup": {
      "propertyOrder": 5,
      "type": "boolean",
      "default": false,
      "configDescription": "descVacuumOnStartup"
    },
    "commitInterval": {
      "propertyOrder": 6,
      "type": "string",
      "format": "timespan",
      "default": "PT10S",
      "configDescription": "descCommitInterval",
      "formatMinimum": "PT1S",
      "visibility": "HideInEngineering"
    },
    "mode": {
      "visibility": "HideInEngineering",
      "propertyOrder": 7,
      "type": "integer",
      "default": 3,
      "configDescription": "descMode",
      "enum": [ 0, 1, 2, 3, 4, 5 ],
      "options": [
        {
          "label": "ENUM_SYNCHRONOUS_EXTRA_PERSIST",
          "value": 0
        },
        {
          "label": "ENUM_SYNCHRONOUS_FULL_PERSIST",
          "value": 1
        },
        {
          "label": "ENUM_SYNCHRONOUS_FULL_MEMORY",
          "value": 2
        },
        {
          "label": "ENUM_SYNCHRONOUS_NORMAL_PERSIST",
          "value": 3
        },
        {
          "label": "ENUM_SYNCHRONOUS_OFF_PERSIST",
          "value": 4
        },
        {
          "label": "ENUM_SYNCHRONOUS_OFF_MEMORY",
          "value": 5
        }
      ]
    }
  },
  "required": [
    "mode",
    "historizedSymbolList",
    "inMemory",
    "maxBackups",
    "enableBackup",
    "vacuumOnStartup",
    "commitInterval"
  ],
  "type": "object",
  "additionalProperties": false
}

=== masacdotio/251402-MGNBALL/251402-MGNBALL/HMI/Server/TcHmiSqliteHistorize/TcHmiSqliteHistorize.Config.default.json
{
    "commitInterval": "PT10S",
    "enableBackup": true,
    "historizedSymbolList": {
        "ADS.PLC1.HMI.stToHMI.stHistory.bShift1": {
            "interval": "PT15M",
            "maxEntries": 24,
            "recordingEnabled": true,
            "rowLimit": 100000
        },
        "ADS.PLC1.HMI.stToHMI.stHistory.bShift2": {
            "interval": "PT15M",
            "maxEntries": 24,
            "recordingEnabled": true,
            "rowLimit": 100000
        },
        "ADS.PLC1.HMI.stToHMI.stHistory.bShift3": {
            "interval": "PT15M",
            "maxEntries": 24,
            "recordingEnabled": true,
            "rowLimit": 100000
        },
        "ADS.PLC1.HMI.stToHMI.stHistory.iNOK": {
            "interval": "PT15M",
            "maxEntries": 24,
            "recordingEnabled": true,
            "rowLimit": 100000
        },
        "ADS.PLC1.HMI.stToHMI.stHistory.iOK": {
            "interval": "PT15M",
            "maxEntries": 24,
            "recordingEnabled": true,
            "rowLimit": 100000
        }
    },
    "inMemory": false,
    "maxBackups": 1,
    "mode": 3,
    "vacuumOnStartup": false
}
